### ISSUE TITLE
Does the svg-overlay plugin have any software license?

### ISSUE THREAD

**Issue by eriksjolund** [openseadragon/svg-overlay#11]
Does the svg-overlay plugin have any software license?
I don't see any LICENSE.txt file in the source code tree.

**Comment by iangilman** [comment]
Good point! We should probably use BSD to match OpenSeadragon: 

https://github.com/openseadragon/openseadragon/blob/master/LICENSE.txt

**Comment by leesei** [comment]
This can be closed

**Comment by iangilman** [comment]
Good catch, thanks!
