### ISSUE TITLE
Resize overlay on viewer.resize

### ISSUE THREAD

**Issue by IllyaMoskvin** [openseadragon/svg-overlay#18]
It seems that resizing the window triggers the `viewer.animate` event, which should in theory resize the overlay, but I've found that it consistently gets "decalibrated" from the viewer when resizing the window, especially during sudden resize events, such as switching from maximized to windowed mode.

I hot-patched it in my app, but it seems like a really easy fix to incorporate into the plugin, so I'll have a PR your way shortly.

**Comment by iangilman** [comment]
Fixed by #19
