### ISSUE TITLE
Best approach to "only-svg" view

### ISSUE THREAD

**Issue by vortice3D** [openseadragon/svg-overlay#31]
Hi **everywere**:

I need to find the best implementation for a OSD viewer showing a electrical circuit loaded from a SVG file.

That is, all the info comes from a SVG file and so is not a "overlay", in a proper way, but the main information container, as the background "image" is only a "dummy" solid color (white) actually.

In order to generate that background, I can think in several options: 

1. hack it in a really dirty way, by means of a "premeditated" invalid tileSource URL;
2. using an image placeholder consisting in a solid color PNG with an enough resolution;
3. render the SVG as a rasterized image (i.e. again PNG) with an enough resolution.

All these alternative solutions do not appear to be very elegant, so... any advice on it?

**Comment by iangilman** [comment]
I guess the first question is why use OSD for this? I assume you want the zooming/panning navigation, but it's best to be sure. 

How big is your SVG in bytes? Is it okay to load it all at once, or is the whole thing big enough that it would cause a long wait? If it is that big, you're probably better off rendering it to a rasterized image and turning it into a tile set. 

If you did want to pursue breaking the SVG up into SVG-based tiles, that would probably be a bit of work. I've got some thoughts here: 

https://twitter.com/DenubisX/status/1006698407564460033

If the SVG is small enough to load all at once, you could certainly use the SVG overlay, but yes you would still need an image in OSD, I think, to generate the boundary the user zooms within. You could do this with a super tiny image though, probably even just a single pixel. Like so:

```
maxZoomPixelRatio: Infinity,
tileSources: {
    tileSource: {
        type: 'image',
        url: 'pixel.jpg'
    },
    width: 1000
}
```

It would certainly be more elegant to not require an image at all, but that would involve changes to OSD itself. If you're interested in pursuing that, I can help point you in the right direction. That said, the single pixel image solution doesn't seem like too terrible of a hack :)

**Comment by iangilman** [comment]
BTW, I'm tagging this issue as a question. If you do want to pursue being able to load SVGs directly into OSD without raster images, you can file an issue in the OSD repository, and we can tag that with "enhancement".

**Comment by vortice3D** [comment]
Hi **Ian**, and as always thank you very much for your immediate support.

Answering your first question: yes I want to zoom/pan my SVGs and, well, as I'm using OSD already in the case of rasterized images, it would be nice not need to use/learn another library for the vector ones.

The SVGs I'm using are really small (around 250KB), that's a very good thing of a middle-complexity vector graphics for the case of CAD-like designs. That way I don´t need to split in tiles my files at all.

About the single pixel image, I find it very convenient and BTW similar as texture techniques used with 3D texturing in other kind of projects (WebGL). The problem here (and of course with any other solution not using a "featured" rasterized image) is the lack of image in the Navigator view, as I think the SVG-overlay is not shown on it (if I'm not wrong) so you see there only a white (if  this is the color chosen for the "pixel" fie) background.

Best regards.

**Comment by iangilman** [comment]
Good point! Well, perhaps the simplest thing would be to make another copy of the SVG and lay it in the navigator element. Since the navigator doesn't zoom or pan, you only have to position it once. You can probably do this without messing with the OSD code at all.

**Comment by vortice3D** [comment]
Thanks for your advice **Ian**.

Anyway, how can I implement this technique?

I mean, the **Navigator** object doesn't expose a **Viewer** property (as the **OSD** singleton does) I can use to retrieve the svg-overlay by means of a call to its **svgOverlay** method. Isn't it?

**Comment by iangilman** [comment]
I'm thinking just straight JavaScript:

```
        var img = document.createElement('img');
        img.src = 'foo.svg';
        img.style.position = 'absolute';
        img.style.left = 0;
        img.style.top = 0;
        img.style.width = '100%';
        viewer.navigator.canvas.appendChild(img);
```

**Comment by vortice3D** [comment]
Hi Ian:

First of all I'd like to apologize for my lack of answer to your info. I'm out of office at the moment since last week and could't read this thread.

Said this, thanks for so valuable info, I understand now that it is done under a basic DOM schema. The case is that I thought I needed to "hook" something with the OSD engine in order to not breaking the whole functionality.

Best regards.

**Comment by vortice3D** [comment]
Hi Ian:

First of all I'd like to apologize for my lack of answer to your info. I'm out of office at the moment since last week and couldn't read this thread.

Said this, thanks for so valuable info, I understand now that it is done under a basic DOM schema. The case is that I thought I needed to "hook" something with the OSD engine in order to not breaking the whole functionality.

Best regards.

**Comment by iangilman** [comment]
No worries; thank you for the follow up. Yes, in this case I think it's perfectly safe to use basic DOM.

**Comment by vortice3D** [comment]
Hi again **Ian**:

I'm trying to fine-tune the behavior of this approach to a SVG viewer we've been talking about along this thread.

This way, one think I'd wish to implement more properly is the scaling of the display-region-rectangle of the navigator according to the size of the SVG in the viewport, the same way that is implemented natively by OSD in the case of raster images.

Obviously now both views (navigator and viewport) are shown disconnected in terms of the display-region-rectangle, as the adopted solution (**_viewer.navigator.canvas.appendChild(img)_**) is mainly "cosmetic".

Any point about this?

**Comment by vortice3D** [comment]
Hi again:

First of all, as you can see I've mistakenly closed this thread and immediately reopened it. Can you fix/delete those events?

In order to complete my needs (and I think of everybody) for this "only-SVG" scenario we are talking about, I see now that I can´t zoom-in nor out freely (I can only zoom-out a bit indeed).

Maybe this can be related to the mentioned "problem" with the "display-region"? I'm assuming now that, in order to achieve a the most similar behavior with the raster images one, is needed to tweak more properties of the OSD engine that the little ones I've considering. Isn´t it?

Kind regards.

**Comment by vortice3D** [comment]
Ok, I think that in order to use the 1-pixel background (raster) solution and, at the same time, getting a correct OSD interactive scaling behavior, I need to scale the SVG according to my needs of visualization.

I'm trying to understand that numbers now.

**Comment by iangilman** [comment]
I'm happy to take a look if you can share a link... perhaps a CodePen?

**Comment by vortice3D** [comment]
Hi **Ian**:

As always, **thank you very much** for your support. That is what really matters when using open source sw, and makes an engine to behave a standard "de facto", as OSD is when talking about pan-zoom engines.

Said this, a **codepen** could be a bit complicated in my case, but I could try it if you think is necessary. However, maybe it could be enough to explain the problematic behavior with the help of some graphical assets.

**Sample 1)**
Using:
```
osdViewer.open({
  tileSource : {
    buildPyramid : false,
    type : "image",
    url : _VIEWER_BLUEPRINT_BG
  },
  width : 1
});
```
I get not image in viewport, as it is really huge:

![image](https://user-images.githubusercontent.com/1760601/43950328-4dfcb9e4-9c90-11e8-92c0-879c7d7c37e2.png)



**Sample 2)**
When using:
```
osdViewer.open({
  tileSource : {
    buildPyramid : false,
    type : "image",
    url : _VIEWER_BLUEPRINT_BG
  },
  width : 10
});
```
thinks get better, but origin and extent of "viewport" and "navigator" image don't match. Also I can´t zoom-in the viewport at all, and only zoom-out in a negligible amount:

![image](https://user-images.githubusercontent.com/1760601/43950442-94aa74f8-9c90-11e8-9bb5-60d22b3b8db6.png)


So, basically, I experiment some degree of "dis-matching" between the part (origin and extension) of the SVG shown in the "viewport" and the one in the "navigator". All this is managed under-the-hood for the OSD engine when a raster image is used, but I'd need to resemble it when using SVG ones.

Also I can´t zoom-in or out in a proper way. I think it can be a side-effect of the only 1px raster background image, isn't it?

Please note also that the SVG shown in the navigator window has a bit of left offset, but I think this is a issue I'll have to tweak from CSS.

Best regards.

_**P.S.: _VIEWER_BLUEPRINT_BG points to a 1px PNG file, as cleverly suggested by you.**_

**_P.S.: The svg opening tag is specified like this:_**

```
<svg xmlns="http://www.w3.org/2000/svg"
	version="1.1"
	height="8.5in"
	width="11in"
	viewBox="0,0,11,8.5">
```

**Comment by iangilman** [comment]
Yes, I think we can talk through it here. 

Basically you need to align your "bg" image to your SVG. One thing I'm realizing is a single pixel actually won't do, as the aspect ratios need to agree. Looks like your SVG is 11 inches by 8.5 inches. That's a 11:8.5 aspect ratio, or 22:17 when converted to whole numbers. So, your BG image should be 22px by 17px, and that way the aspect ratio will match.

As for the width you give it, it's funny adding inches into the mix, but it does seem to be working. When you specified `width: 10` you seem to be getting most of the image, so I imagine `width: 11` (to match the 11 inches of the SVG) would be perfect.

As for not being able to zoom in or out very much, the default zoom limits are based on the pixels of your BG image, so you'll have to change the limits. There are a few options for this you can see listed here:

http://openseadragon.github.io/docs/OpenSeadragon.html#.Options

If you want to completely disable zoom limits, you can use: 

```
minZoomImageRatio: 0,
maxZoomPixelRatio: Infinity
```

There may be other things that need tweaking, but that's a good start.

**Comment by vortice3D** [comment]
Good morning (CET) **Ian**:

Ok, I see. Your tips put me definitively in the right way.

However, one think I'm trying to figure out how can be done is setting "zoom image ratio" (min and max) not in the Viewer constructor but dynamically, as I'm using the same viewer object to toggle from raster to vector image. If I'm not wrong there's not way of passing them (zoom rations) as a parameters to the **Viewer.open()** method and, on the other hand, I can´t find a **setMinZoomImageRatio** nor **setMaxZoomImageratio** method for the viewer object.

Kind regards.

**Comment by vortice3D** [comment]
Hi again **Ian**:

Please let me return now briefly to the positioning of the SVG in the navigator viewport.

The case is that I'm following the code previously suggested by you in this same thread:

```
    ...
    viewer.navigator.canvas.appendChild(img);
```

This way, I experiment a vertical offset for the SVG shown in the Navigator viewport, as it is styled to be positioned, no centered vertically (as the white BG is indeed shown), but at a specific distance (0 in this case) from its parent (canvas) element:

![image](https://user-images.githubusercontent.com/1760601/44081377-e274f098-9fae-11e8-87c6-b4f951c88911.png)
 

Inspecting now the markup of the Navigator element I find the following hierarchy is (identified by the applied class when available):

**openseadragon-container**

-->**openseadragon-canvas**
---->**canvas**
---->**div**
---->**img**

-->**displayregioncontainer**
---->**displayregion**


I'm going to try with the several techniques for centering an img vertically into its container div, as you are doing for the canvas (I suppose so), but I prefer to consult you before, so maybe you can see something I may have missed at this point.

Best regards.

**Comment by vortice3D** [comment]
Hi **Ian**, I'm tweaking a bit here and there the navigator styling and, well, I've got to something that is more close to an ideal solution.

The case is that I'm implementing the following CSS solution for centering unknown-height things vertically (I'll go for a more cross-browser and probably know-height solution when I get rid of this first approach):

```
...
position: absolute;
top: 50%;
transform: translateY(-50%);
width: 100%;
...
```

...in order to get this:

![image](https://user-images.githubusercontent.com/1760601/44085864-0f9e2ad8-9fbb-11e8-8fda-b02f32dbde9c.png)



As you can see, I'm still experimenting some kind of vertical offset (that should be shown also in the Navigator), I think is related with the existence of a padding in the **openseadragon-canvas** container div, but the case is that I can´t see nothing of that when inspecting that element.

Best regards.

**Comment by iangilman** [comment]
For your first question: Yes, it appears there's no explicit API for changing the minZoomImageRatio (perhaps there should be). It looks like you can do so by setting a new value into `viewer.viewport.minZoomImageRatio` however. 

Regarding the navigator placement: Is your navigator a dynamic size? If not, the easiest solution would be to explicitly set it with `top` and `left` values that work. Otherwise, seems like you're on the right track. You may have to tweak it manually... for instance, `top: calc(50% + 5px)`.

It is odd that it's off in the viewer, since it looks pretty perfectly centered in the navigator. Anyway, if you tweak it, is it possible to get it adjusted properly (and therefore it's just a matter of positioning), or does it also need to be scaled some?

**Comment by vortice3D** [comment]
Hi **Ian**, and as always thank you very much for your immediate response.

About setting the minimum (maximum) ZoomImageRatio by means of **viewport**, I'll do so.

The v-offset I've been experimenting was my fault, as I was doing tests with other SVG files and then forgot to change the background file size to the necessary 22x17px. After fixing it the circuit is centered all right:

![image](https://user-images.githubusercontent.com/1760601/44191680-adb8c300-a12c-11e8-9934-c8a62f93e7fe.png)

About the positioning of it all via CSS styling I need a responsive behavior, so the following is working well for such a dynamic scenario:

```
.viewport_navigator img {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    width: 100%;
}
```

Of course, It can be done also with the help of **flexbox** in the parent element (viewer.navigator.canvas) but I prefer not to touch any internal OSD engine styles.

Best regards.

**Comment by iangilman** [comment]
Fantastic. I'm glad we're documenting this process here in this thread, in case others want to do something similar.

**Comment by vortice3D** [comment]
Yes, I think so **Ian**.

With the help of this thread and the other one about **[Loading an external SVG file](https://github.com/openseadragon/svg-overlay/issues/29)** (started by **Salitehkat**)  I think it's possible to have a good idea of how to implement real-world SVG pan-zoom functionalities for any web development, with the aid of OSD.

Again, thank you very much for your support.

Best regards.

**Comment by iangilman** [comment]
Excellent. When your project is ready to share, I'd love it if you could add it to http://openseadragon.github.io/examples/in-the-wild/ :)
