### ISSUE TITLE
Managing of overlays

### ISSUE THREAD

**Issue by tobiasschweizer** [openseadragon/svg-overlay#32]
I had a look at the source of http://openseadragon.github.io/svg-overlay/demo.html:

```javascript
var overlay = this.viewer.svgOverlay();

                    var d3Rect = d3.select(overlay.node()).append("rect")
                        .style('fill', '#f00')
                        .attr("x", 0.5)
                        .attr("width", 0.25)
                        .attr("y", 0.5)
                        .attr("height", 0.25);
```

I am wondering if an overlay should be added using the the viewer's method `addOverlay` (https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#addOverlay).

If I understand correctly, the viewer then keeps track of the overlays and removes them when `viewer.clearOverlays` is called.

I have a use case which requires overlays to be redrawn (https://github.com/dhlab-basel/Knora-ui/pull/168).

**Comment by iangilman** [comment]
No, this plugin doesn't use the OSD overlay system at all. It just gives you an SVG node and it's up to you to add/remove items from it using normal SVG calls (or something like d3 if you want).

**Comment by tobiasschweizer** [comment]
I understand, thanks for the clarification.

I guess this is a demo where the viewer's overlay system (not SVG, but HTML) is used: https://github.com/openseadragon/openseadragon/blob/0043956e2ab89ef1b027e12469e6808be9edae0c/test/demo/overlay.html

**Comment by iangilman** [comment]
Yes, that's correct.
