### ISSUE TITLE
openseadragon svg-overlay d3 draggable elements

### ISSUE THREAD

**Issue by dbhuvanapalli** [openseadragon/svg-overlay#38]
I'm trying to implement something similar to the following example.
http://bl.ocks.org/zloysmiertniy/0ab009ca832e7e0518e585bfa9a7ad59

How can I get the new image coordinates after the drag event ends from the delta coordinates?

**Comment by iangilman** [comment]
The drag event includes a `position` property; you should use that instead of the delta. Just remember to convert it to viewport coordinates with `pointFromPixel`.

**Comment by dbhuvanapalli** [comment]
Hi Ian, 
I did try that but I dont think they give the image coordinates. This is the code that I used, and none of them give me the new position image coordinates. The element in the mouse tracker is node, does that make any difference?

> d3.select("#"+HTMLid.toString()).each(function() { 
>         var node = this;
>         new OpenSeadragon.MouseTracker({
>         element: node,
>         dragHandler: function(event){
>             var viewportDelta = viewerObj.viewport.deltaPointsFromPixels(event.delta); 
>             var d3node = d3.select(node); 
>             var transformobj= transformToObject(d3node.attr('transform'));
>             transformobj.translate[0]=Number(transformobj.translate[0])+Number(viewportDelta.x);
>             transformobj.translate[1]=Number(transformobj.translate[1])+Number(viewportDelta.y);
>             d3node.attr("transform",objectToTransform(transformobj));
>         },
>         dragEndHandler: function(event){
>             var viewportPoint = viewerObj.viewport.pointFromPixel(event.position);
>             var imagePoint = viewerObj.viewport.viewportToImageCoordinates(viewportPoint);
> 	    console.log(event.position);
> 	    console.log(viewportPoint);
> 	    console.log(imagePoint);
>         }
>     }).setTracking(true);
>    });
> 

![image](https://user-images.githubusercontent.com/49796596/92048239-31b26780-ed55-11ea-8489-e8900b277566.png)

**Comment by msalsbery** [comment]
> I did try that but I dont think they give the image coordinates...The element in the mouse tracker is node, does that make any difference?

The `position` property's value is relative to the element the `MouseTracker` is attached to!

**Comment by dbhuvanapalli** [comment]
Got it, Thank you @msalsbery
