### ISSUE TITLE
SVG adds animation but the page has no effect

### ISSUE THREAD

**Issue by Canees** [openseadragon/svg-overlay#42]
display：
![微信图片_20210430095741](https://user-images.githubusercontent.com/40012261/116639199-87015000-a99a-11eb-8a5b-2a54b0b15bf3.png)

**Comment by iangilman** [comment]
Does the animation work when it's not attached to the SVG overlay? Theoretically the SVG overlay shouldn't impact animation. Can you share a demo of the problem?

**Comment by Canees** [comment]
> 未连接到SVG叠加层时，动画可以正常工作吗？从理论上讲，SVG覆盖不应该影响动画。您可以分享该问题的演示吗？

No, the animation is invalid when SVG adds the animate tag.SVG works when adding CSS animations, but scaling affects other elements.Part of the demo code：
init it:
      svgOverlay(OpenSeadragon)
      let showScale = 0.125
      this.viewer = OpenSeadragon({
        id: 'openseadragon1PP',
        prefixUrl: './../assets/images/planImages/',
        showNavigationControl: true,
        showZoomControl: false,
        showHomeControl: false,
        showFullPageControl: false,
        showFlipControl: false,
        showRotationControl: false,
        zoomPerClick: 1,
        navigationControlAnchor: OpenSeadragon.ControlAnchor.TOP_LEFT,
        showNavigator: true,
        navigatorPosition: 'BOTTOM_RIGHT',
        navigatorSizeRatio: showScale,
        minZoomLevel: 1,
        maxZoomLevel: 4,
        defaultZoomLevel: 4,
        debugMode: false,
        visibilityRatio: 1.0,
        constrainDuringPan: false,
        tileSources: {
          height: this.planHeight,
          width: this.planWidth,
          tileSize: 512,
          minLevel: 9,
          maxLevel: 15,
          getTileUrl: function (level, x, y) {
            level = level - 9
            level = Math.pow(2, level)
            if (level < 1) {
              level = showScale
            }
            return that.tile_path + level + '/' + x + '_' + y + '.jpg'
          },
          tileExists (level, x, y) {
            level = level - 9
            level = Math.pow(2, level)
            return (
              y < level * Math.max(that.planHeight / that.planWidth, 1) &&
              x < level * Math.max(that.planWidth / that.planHeight, 1)
            )
          }
        }
      })

      this.viewer.addHandler('canvas-drag', function () {
        that.isUpdate = false
      })
      this.viewer.addHandler('canvas-release', function () {
        that.isUpdate = true
      })
      this.viewer.addHandler('open', function () {
        that.mapInit = true
      })
      this.overlay = this.viewer.svgOverlay().node()
add svg:
  let svgPath = document.createElementNS(this.svgNS, 'polyline')
      svgPath.setAttributeNS(null, 'points', points)
      svgPath.style.stroke = pointColor
      svgPath.style.strokeWidth = `${this.ring_width * this.scale}px`
      svgPath.style.strokeDasharray = 'none'
      svgPath.style.fill = 'none'
      svgPath.style.opacity = opacity
 let animate = document.createElement("animate")
    animate.setAttribute("attributeName","fill-opacity");
    animate.setAttribute("values","1;0;1");
    animate.setAttribute("dur","1s");
    animate.setAttribute("repeatCount","indefinite");
svgPath.append(animate)
this.overlay.append(svgPath)

**Comment by Canees** [comment]
> Does the animation work when it's not attached to the SVG overlay? Theoretically the SVG overlay shouldn't impact animation. Can you share a demo of the problem?

No, the animation is invalid when SVG adds the animate tag.SVG works when adding CSS animations, but scaling affects other elements.Part of the demo code：
init it:
```
      svgOverlay(OpenSeadragon)
      let showScale = 0.125
      this.viewer = OpenSeadragon({
        id: 'openseadragon1PP',
        prefixUrl: './../assets/images/planImages/',
        showNavigationControl: true,
        showZoomControl: false,
        showHomeControl: false,
        showFullPageControl: false,
        showFlipControl: false,
        showRotationControl: false,
        zoomPerClick: 1,
        navigationControlAnchor: OpenSeadragon.ControlAnchor.TOP_LEFT,
        showNavigator: true,
        navigatorPosition: 'BOTTOM_RIGHT',
        navigatorSizeRatio: showScale,
        minZoomLevel: 1,
        maxZoomLevel: 4,
        defaultZoomLevel: 4,
        debugMode: false,
        visibilityRatio: 1.0,
        constrainDuringPan: false,
        tileSources: {
          height: this.planHeight,
          width: this.planWidth,
          tileSize: 512,
          minLevel: 9,
          maxLevel: 15,
          getTileUrl: function (level, x, y) {
            level = level - 9
            level = Math.pow(2, level)
            if (level < 1) {
              level = showScale
            }
            return that.tile_path + level + '/' + x + '_' + y + '.jpg'
          },
          tileExists (level, x, y) {
            level = level - 9
            level = Math.pow(2, level)
            return (
              y < level * Math.max(that.planHeight / that.planWidth, 1) &&
              x < level * Math.max(that.planWidth / that.planHeight, 1)
            )
          }
        }
      })

      this.viewer.addHandler('canvas-drag', function () {
        that.isUpdate = false
      })
      this.viewer.addHandler('canvas-release', function () {
        that.isUpdate = true
      })
      this.viewer.addHandler('open', function () {
        that.mapInit = true
      })
      this.overlay = this.viewer.svgOverlay().node()
```
add svg:
```
  let svgPath = document.createElementNS(this.svgNS, 'polyline')
      svgPath.setAttributeNS(null, 'points', points)
      svgPath.style.stroke = pointColor
      svgPath.style.strokeWidth = `${this.ring_width * this.scale}px`
      svgPath.style.strokeDasharray = 'none'
      svgPath.style.fill = 'none'
      svgPath.style.opacity = opacity
 let animate = document.createElement("animate")
    animate.setAttribute("attributeName","fill-opacity");
    animate.setAttribute("values","1;0;1");
    animate.setAttribute("dur","1s");
    animate.setAttribute("repeatCount","indefinite");
svgPath.append(animate)
this.overlay.append(svgPath)
```

**Comment by iangilman** [comment]
[I added ``` to your code samples above so they format correctly here.]

My recommendation would be to try to get it working outside of OSD first so you have fewer moving parts. I'm guessing the issue is unrelated to OSD. 

One thing I see in your code is that the `animate` should probably be created with `createElementNS`.
