### ISSUE TITLE
Setting Width of Canvas for DZI Tile Source Firefox Issue

### ISSUE THREAD

**Issue by gerstej9** [openseadragon/svg-overlay#47]
Hi @iangilman thank you again for your help on my last issue with the overlay plugin. I am now running into an issue with tileSource sizing to circumvent the Firefox SVG issue other's have mentioned.

In a prototype of the application I am trying to create I am able to use this code 

`        var viewer = OpenSeadragon({
            id: 'a6',
            prefixUrl: 'https://openseadragon.github.io/openseadragon/images/',
            tileSources: {
                tileSource: './7045-A7-NEUN.dzi',
                width: 1000,
            }
        });`

Specifically you can see in the TileSources I am able to set a tileSource property with the url and a width related to the tileSource. This allows me to multiply my svgOverlay width and height by 1000 and it fixes the issue with Firefox.

`            var d3Svg = d3.select(overlay.node())
            .append("svg:image")
            .attr("xlink:href", "./7045-A7-NEUN.svg")
            .attr("width", 1000)
            .attr("height", ratioComputedHeight * 1000)
        })`

When I attempt to utilize the same tileSource formatting in my React application I receive this error 

`No TileSource was able to open undefined [object Object]`

Setting the width of the tileSource in my sample application was a huge breakthrough for getting Firefox to work with the SVG but now I'm unable to replicate that in my application.

Any help you can offer would be greatly appreciated, thank you in advance!

**Comment by iangilman** [comment]
Hmm... It should work the same in React. Perhaps there's some subtle difference in how you are expressing it there? Unfortunately, the `tileSources` option is so flexible it can be hard to work with. Can you share a code snippet of how you're doing it in React?

**Comment by gerstej9** [comment]
Yeah definitely and as always thank you again for the help!
Here is the version in React that is currently working in Chrome. I had abandoned trying to use tileSources as a property in the initialization of OpenSeaDragon because of the issues I was running into and instead and using the viewer.open with a string to a .dzi source. Below this code is an example of my prototype where I am able to use the tileSources property on intialization and I can pass in a tileSource width which I haven't been able to do in this React code
```
 useEffect(() => {
        if (tileSource && viewer) {
            viewer.open(tileSource);
        }
        // viewer needs to be opened again only on image change and not on viewer update.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [tileSource]);`

    const InitOpenseadragon = () => {
        viewer && viewer.destroy();
        setViewer(
            OpenSeaDragon({
                id,
                ...OSD_CONFIGRATION,
            })
        );
    };
```

```
useEffect(() => {
        InitOpenseadragon();

        return () => {
            viewer && viewer.destroy();
        };
        // Initializing open seadragon should happen only on mount, and not on viewer update.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // On viewer tileSource change the svg overlay needs to be updated
    useEffect(() => {
        if (viewer) {
            viewer.addHandler('open', () => {
                // remove any existing svg overlays on image change
                selectAll('.svgOverlay').remove();
                const overlay = OsdSvgOverlay(viewer);
                const ratioComputedHeight = 1 / viewer.source.aspectRatio;
                svgSource &&
                    select(overlay.node())
                        .append('svg:image')
                        .attr('xlink:href', svgSource)
                        .attr('class', 'svgOverlay')
                        .attr('width', 1)
                        .attr('height', ratioComputedHeight);
            });
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [tileSource]);
```

Prototype code with working tileSource width Properties
``` 
var viewer = OpenSeadragon({
            id: 'a6',
            prefixUrl: 'https://openseadragon.github.io/openseadragon/images/',
            tileSources: {
                tileSource: './7045-A7-NEUN.dzi',
                width: 1000,
            }
        });
```

```
var overlay = viewer.svgOverlay();

        viewer.addHandler('open', function() {
            var overlay = viewer.svgOverlay();
            var ratioComputedHeight = (1 / viewer.source.aspectRatio)
            console.log(ratioComputedHeight, viewer.viewport)
            var d3Svg = d3.select(overlay.node())
            .append("svg:image")
            .attr("xlink:href", "./7045-A7-NEUN.svg")
            .attr("width", 1000)
            .attr("height", ratioComputedHeight * 1000)
        })
```

So you can see in the prototype I'm setting a tileSource within tileSources as well as a width. I tried the same syntax in the React code and it threw an error. I also tried
`tileSources : {url: dziSource, width: 1000}` which didn't upset the linter but it failed to load with an error along the times of "cannot read undefined of [object][object]."

Any thoughts come to mind? Is there any way to update a tileSource width after opening it?
Your help is much appreciated!

**Comment by iangilman** [comment]
You can use `open` just the same as `tileSources`. You would do it like so: 

```
viewer.open({ tileSource: tileSource, width: 1000 });
```

And yes, you can change the width of images after they are loaded as well. For instance: 

```
viewer.world.getItemAt(0).setWidth(1000, true);
```

BTW, for your code examples, you wrapped them in a single backtick, but for multi-line examples, you should use three backticks (```). I've gone ahead and fixed yours so they're easier to read :)

**Comment by gerstej9** [comment]
Ah thank you so much Ian and roger on the backticks good to know moving forward. Can't thank you enough for all your help, you're effort to respond so promptly is really really appreciated.

**Comment by iangilman** [comment]
Excellent... I'm glad to be of help! If you want, you can try to convince your organization to sponsor OpenSeadragon on https://opencollective.com/openseadragon. 😉

**Comment by gerstej9** [comment]
Yeah that's a great idea! I can't make any promises but I'll definitely ask my supervisor if there is something we can do.

**Comment by iangilman** [comment]
Thank you! If they don't go for it, and you have feedback as to why, I'd love to hear that as well. Feel free to contact me directly if you don't want to do it here in public 😄

**Comment by gerstej9** [comment]
Yeah that sounds good I'll definitely let you know either way once I'm able to get an answer from my org.

**Comment by gerstej9** [comment]
Hey @iangilman I wanted to follow up with you, my manager has put a request in to higher ups to see if there is anything we can do in the form of sponsorship for OSD. 

On a separate note I realized that while ```viewer.open({ tileSource: tileSource, width: 1000 });``` worked for getting the overlay to open and be displayed on firefox it broke the ability to zoom in and out of the image. I got so excited that the overlays were showing in Firefox at the time that I forgot to test the zoom doh!

**Comment by iangilman** [comment]
> Hey @iangilman I wanted to follow up with you, my manager has put a request in to higher ups to see if there is anything we can do in the form of sponsorship for OSD.

Wonderful, thank you! 

> On a separate note I realized that while viewer.open({ tileSource: tileSource, width: 1000 }); worked for getting the overlay to open and be displayed on firefox it broke the ability to zoom in and out of the image. I got so excited that the overlays were showing in Firefox at the time that I forgot to test the zoom doh!

What other options are you using when creating the viewer? Are you doing anything to limit how far you can zoom? If not, does it seem like it might be an issue with the overlay stealing events from the viewer (I don't expect that's it, since it's usually the other way around, but I have to ask)?

**Comment by gerstej9** [comment]
Thanks Ian as always super grateful for the quick replies. Here are the viewer configurations 
```
OpenSeaDragon({
                id,
                ...OSD_CONFIGRATION,
            })
```

```
 export const OSD_CONFIGRATION = {
    animationTime: 0.5,
    blendTime: 0.1,
    constrainDuringPan: true,
    showZoomControl: false,
    showHomeControl: false,
    showFullPageControl: false,
    maxZoomPixelRatio: 2,
    minZoomLevel: 1,
    visibilityRatio: 1,
    zoomPerScroll: 2,
};,
```

Please let me know if you see anything in there that might be an issue, per your comment maybe maxZoomPixelRation: 2? 

Also I forgot to mention, it will allow zooming in but not zooming out.

**Comment by iangilman** [comment]
I'm guessing it's actually the `minZoomLevel`. I believe the zoom value is relative to the default image width of 1, so when you change the width to 1000, you now start out zoomed at 0.001 or something. You can easily do `viewer.viewport.getZoom()` (after it's loaded and settled) to verify that. 

What is your purpose for using `minZoomLevel`? There's probably a better way to do it, like `minZoomImageRatio` which is relative, rather than absolute.

**Comment by gerstej9** [comment]
Most of the config was originally put together by a dev who is no longer with the team so I couldn't say why they chose to utilize that parameter. I will try the minZoomImageRatio, though, and see if that does the trick. Thanks Ian!

**Comment by gerstej9** [comment]
That seemed to do the trick! All functional on both Chrome and Firefox you rock Ian!

**Comment by iangilman** [comment]
Awesome! :)
