### ISSUE TITLE
href attribute

### ISSUE THREAD

**Issue by Kampii** [openseadragon/svg-overlay#5]
Hi,

My goal is to be able to click on the svg object and trigger the load of new image. For now I am simply trying to add a link. The code below disables the clicktozoom in the circle area, however, it does not display any active link. What is the right correct way to achieve this?

```
                var overlay = this.viewer.svgOverlay();

                var d3Rect = d3.select(overlay.node()).append("circle")
                    .style('fill', '#f00')
                    .style("fill-opacity", .2)
                    .attr("xlink:href", "http://google.com")
                    .attr("cx", 3964)
                    .attr("cy", 2742)
                    .attr("r", 72);

                overlay.onClick(d3Rect.node(), function() {
                    console.log('click', arguments);
                });
```

**Comment by iangilman** [comment]
I don't know enough about SVG to know if that should work on a regular SVG image (one that's not part of the OpenSeadragon SVG Overlay). Should it? If so, we may have a bug. 

At any rate, what do you mean by "display any active link"? Are you expecting to see text with an underline? A pointer cursor? Are you expecting it to take you to a new page when you click on it?

**Comment by Kampii** [comment]
So I used the href attribute definition from this demo (http://bl.ocks.org/d3noob/8150631) and I would like to have a pointer cursor (the hand) when user hovers the mouse over it and take the user to the link when clicked.

I was hoping that the attribute would work and then my next step would be to figure out how to load a new image on the click.

PS. I didn't want to spam you, but I did found the setting for the dragging animation (inertia) :) Thanks

**Comment by Kampii** [comment]
Alright.. After some more testing I have found out how to get the link, please see the code below:

```
                overlay.onClick(d3Rect2.node(), function() {
                                                    console.log('click', arguments);
                                                    location.href = "http://yahoo.com";
                                                    });
```

**Comment by iangilman** [comment]
Sounds like you don't really want an actual link that would take you away to another page; you just want the cursor to change? That would be as simple as: 

```
d3Rect.style('cursor', 'pointer');
```

If you do want it to be an actual link, you have to nest your circle inside of an `a` element. Take another look at http://bl.ocks.org/d3noob/8150631 and you'll see that's what they're doing.

**Comment by Kampii** [comment]
The "a" element worked great but what I noticed is that the hyperlink doesn't work neither on iOS nor on Android. Is that my  "a" element implementation error or I have to have some additional code that will handle href clicks on mobile devices?

**Comment by iangilman** [comment]
Unfortunately I don't know that much about `a` elements in SVG. Have you tried non-OpenSeadragon `a`/svg elements (such as the bl.ocks example above) on those devices? If we can isolate the problem to OpenSeadragon/svg-overlay, maybe we can patch it. Or if you find that it happens regardless of OSD, maybe someone else has a fix. 

Of course a brute force approach would be to watch for touch events and handle them as appropriate. There are libraries like http://hammerjs.github.io/ to help.

**Comment by Kampii** [comment]
Let me check, thank you for the direction! I will update..

**Comment by Kampii** [comment]
After countless tests here is the best I've got. In this (http://www.c-ev.com/osdragon/hreftest1.html) test I am almost getting there, however, I am not able to get the blue rectangle on top of the image. On the other hand in this test (http://www.c-ev.com/osdragon/hreftest2.html) I get the svg on the image, but the hyperlink does not work on the mobile device even though it works on the PC.

I was playing with the red circle the whole evening and I couldn't get it to work, so I am hoping if there is a way to get that blue rectangle on the image and have it zoom together with it.

**Comment by iangilman** [comment]
Well that narrows it down! Thank you for the great repro...it's helped me track down and fix the issue (see #7). Due to the complicated gesture tracking we have on the viewer, this plugin needed to use the OpenSeadragon.MouseTracker rather than handling the events itself. 

This does mean that you're not going to be able to use `a` elements directly...instead you need to use `overlay.onClick`, which will work on any SVG element. If you want the click to take you to another page, you can still do `location.href = "http://google.com"` or whatever. Also, if you want the pointer cursor to show up on desktop, just use `.style('cursor', 'pointer')` on your d3 object.

**Comment by iangilman** [comment]
Btw, I look forward to seeing the finished app! Let me know when it's ready and we can add it to http://openseadragon.github.io/examples/in-the-wild/ :)

**Comment by Kampii** [comment]
Perfect! If anyone is looking for the code, find it below. Great job Ian, thanks!

```
                var overlay = this.viewer.svgOverlay();

                var d3Rect1 = d3.select(overlay.node())
                    .append("circle")
                    .style('cursor', 'pointer')
                    .style('fill', '#f00')
                    .style("fill-opacity", .8)
                    .attr("cx", 3964)
                    .attr("cy", 2742)
                    .attr("r", 702);

                    overlay.onClick(d3Rect1.node(), function() {
                                    console.log('click', arguments);
                                    location.href = "http://google.com";

                                    });
```
