### ISSUE TITLE
Overlay off when OSD viewport margins set?

### ISSUE THREAD

**Issue by friarpat** [openseadragon/svg-overlay#9]
Not certain if this applies to svg-overlay or OpenSeaDragon.

I'm using svg-overlay to provide a border around the currently hovered image.   All was working well, but I noticed the border was slightly hidden on the left of images (and on the right of images) when I hit the home button on OSD.  I set the viewportMargins option on the OSD viewer to have a left and right margin of 2.   Border now shows properly in the X direction, but the Y is too "low".   In Firebug, I can adjust the y parameter of the  "g transform="translate(x, y) scale(blah) element to raise the border to the right location.  I can also take the other route of reducing the Y of the rectangle that is a child of the "g" element.  The outline has the correct width/height - it's just misplaced in the Y direction.

 I see there is a getBoundsWithMargins for the OSD viewport, but not for the tiledImage.  I'm using the tiledImage.getBounds call to get the size of the border along with the x/y to get the top/left of the rectangle.  

Do I need to do something with the svg-overlay to fix this, or do I need to do something on the OSD side to account for the margins?   There is probably some calculation I can perform to get the correct Y coordinate when using margins - but I'm not seeing it.

Thanks!

**Comment by friarpat** [comment]
My bad - I should have looked at the right side of things when I Home view and left/right margins defined.  On the right side, the overlay is off in both the x and y directions...left is off just in the Y direction (most likely because X is 0)

**Comment by iangilman** [comment]
Good catch! I've just checked in a fix. :)
